import { ProjectEngagement, JobPosting, ProjectDocument } from './types';

export const INITIAL_PROJECTS: ProjectEngagement[] = [
  {
    id: 'tmp-andon',
    title: 'TMP Andon System',
    tagline: 'A hole-by-hole view of where things stand.',
    clientName: 'Toyota Motor Philippines',
    referenceCode: 'TMP-ANDON-01',
    holeNumber: 4,
    par: 4,
    totalYards: 430,
    durationWeeks: 19,
    startDate: 'Jun 2',
    targetCompletionDate: 'Oct 14',
    currentBallT: 0.55,
    progressPercentage: 55,
    waypoints: [
      {
        id: 'wp-1',
        code: 'Start',
        name: 'Hardware install',
        date: 'Jul 18',
        status: 'done',
        t: 0.18,
        pos: { x: 200, y: 92 },
        calloutTitle: 'Hardware install done — Jul 18',
        calloutPosition: 'right',
        description: 'On-site PLC and panel installation completed.',
        deliverableSummary: 'On-site PLC and panel installation completed.',
      },
      {
        id: 'wp-2',
        code: 'WP-02',
        name: 'Integration testing',
        date: 'Aug 5',
        status: 'done',
        t: 0.38,
        pos: { x: 145, y: 185 },
        calloutTitle: 'Integration testing — Aug 5',
        calloutPosition: 'left',
        description: 'Line integration verified against Andon triggers.',
        deliverableSummary: 'Line integration verified against Andon triggers.',
      },
      {
        id: 'wp-3',
        code: 'WP-03',
        name: 'Payment — Phase 2',
        date: 'Due Aug 30',
        status: 'blocked-on-you',
        t: 0.55,
        pos: { x: 133, y: 275 },
        calloutTitle: 'Payment due — Aug 30',
        calloutSubtitle: 'before we proceed',
        calloutPosition: 'left',
        description: 'Required before final configuration begins.',
        deliverableSummary: 'Required before final configuration begins.',
        actionRequired: {
          type: 'payment',
          badgeLabel: 'Action needed from you',
          dueDate: 'Aug 30',
          amount: '$18,500 USD',
          documentTitle: 'Phase 2 Milestones Invoice & Scope Release',
          notes: 'Required before final configuration begins.',
        },
      },
      {
        id: 'wp-4',
        code: 'WP-04',
        name: 'Final sign-off',
        date: 'Sep 25',
        status: 'upcoming',
        t: 0.78,
        pos: { x: 205, y: 365 },
        calloutTitle: 'Final sign-off — Sep 25',
        calloutPosition: 'right',
        description: 'Review and approve completed system.',
        deliverableSummary: 'Review and approve completed system.',
      },
      {
        id: 'wp-5',
        code: 'Finish',
        name: 'Project delivered',
        date: 'Oct 14',
        status: 'upcoming',
        t: 0.98,
        pos: { x: 165, y: 470 },
        description: 'Handover and documentation complete.',
        deliverableSummary: 'Handover and documentation complete.',
      },
    ],
  },
  {
    id: 'boreas-mach4',
    title: 'Project Boreas',
    tagline: 'Hypersonic Leading-Edge Thermal Barrier',
    clientName: 'Aethelgard Defense & Aerostructures',
    referenceCode: 'CW-ENG-8842',
    holeNumber: 4,
    par: 4,
    totalYards: 430,
    durationWeeks: 18,
    startDate: 'May 12, 2026',
    targetCompletionDate: 'Sep 28, 2026',
    currentBallT: 0.58, // Positioned right at WP-4 where client action is required
    waypoints: [
      {
        id: 'wp-1',
        code: 'TEE-01',
        name: 'Tee-off: PDR & Boundary Layer Spec',
        date: 'May 12',
        status: 'done',
        t: 0.05,
        pos: { x: 175, y: 48 },
        deliverableSummary: 'Aerothermal boundary conditions frozen, preliminary mesh verified across Mach 3.8 to 4.4 range.',
      },
      {
        id: 'wp-2',
        code: 'WP-02',
        name: 'Inconel 718 Hot-Fire Coupon Run',
        date: 'Jun 02',
        status: 'done',
        t: 0.23,
        pos: { x: 95, y: 135 },
        deliverableSummary: '1,420°C high-enthalpy arc-jet tunnel validation completed with zero ablative delamination.',
      },
      {
        id: 'wp-3',
        code: 'WP-03',
        name: 'Transition CFD Shock Tunnel Match',
        date: 'Jun 28',
        status: 'done',
        t: 0.42,
        pos: { x: 220, y: 228 },
        deliverableSummary: 'Schlieren optical imaging validated shock angle within 0.4° of computational fluid dynamic model.',
      },
      {
        id: 'wp-4',
        code: 'WP-04',
        name: 'Critical Design Review & Seal Spec',
        date: 'Jul 22',
        status: 'blocked-on-you',
        t: 0.58,
        pos: { x: 135, y: 320 },
        deliverableSummary: 'Complete CAD envelope, thermal stress maps, and cryogenic primary seal specification packet.',
        actionRequired: {
          type: 'approval',
          badgeLabel: 'Awaiting your approval',
          dueDate: 'Jul 26',
          documentTitle: 'CDR Thermal-Structural Interface Dossier (v3.2)',
          notes: 'Formal engineering sign-off required on thermal expansion clearances before foundry raw ingot lock.',
        },
      },
      {
        id: 'wp-5',
        code: 'WP-05',
        name: 'Foundry Ingot Pour & Ultrasound NDT',
        date: 'Aug 18',
        status: 'upcoming',
        t: 0.77,
        pos: { x: 205, y: 410 },
        deliverableSummary: 'Non-destructive ultrasonic phased array inspection of high-nickel billet core structure.',
        actionRequired: {
          type: 'payment',
          badgeLabel: 'Payment due — Aug 30',
          dueDate: 'Aug 30',
          amount: '$42,500 USD',
          notes: 'Tranche 3 procurement & foundry tooling retainer payment to release CNC machining path.',
        },
      },
      {
        id: 'wp-6',
        code: 'PIN-06',
        name: 'Pin: Flight-Qualified Assembly Delivery',
        date: 'Sep 28',
        status: 'upcoming',
        t: 0.95,
        pos: { x: 165, y: 505 },
        deliverableSummary: 'CMM inspection certificate, environmental seal validation report, and crated assembly handover.',
      },
    ],
  },
  {
    id: 'daedalus-cryo',
    title: 'Project Daedalus',
    tagline: 'Deep-Well Cryogenic Cavitation Sensor',
    clientName: 'North Sea Deep Energies Ltd.',
    referenceCode: 'CW-ENG-7910',
    holeNumber: 7,
    par: 3,
    totalYards: 215,
    durationWeeks: 10,
    startDate: 'Jun 15, 2026',
    targetCompletionDate: 'Aug 24, 2026',
    currentBallT: 0.35,
    waypoints: [
      {
        id: 'dwp-1',
        code: 'TEE-01',
        name: 'Tee-off: Acoustic Resonator Spec',
        date: 'Jun 15',
        status: 'done',
        t: 0.08,
        pos: { x: 170, y: 55 },
        deliverableSummary: 'Cryogenic piezo-electric crystal finite element model completed.',
      },
      {
        id: 'dwp-2',
        code: 'WP-02',
        name: 'Liquid Nitrogen Immersion Test',
        date: 'Jul 04',
        status: 'current',
        t: 0.35,
        pos: { x: 110, y: 190 },
        deliverableSummary: '77 Kelvin thermal cycling test underway at Edinburgh cryogenic test facility.',
      },
      {
        id: 'dwp-3',
        code: 'WP-03',
        name: 'Telemetry Firmware V1 Acceptance',
        date: 'Jul 28',
        status: 'upcoming',
        t: 0.65,
        pos: { x: 215, y: 340 },
        deliverableSummary: '100kHz real-time sensor DSP demodulator bitstream validation.',
        actionRequired: {
          type: 'approval',
          badgeLabel: 'Awaiting your approval',
          dueDate: 'Jul 29',
          documentTitle: 'Telemetry Protocol Spec v1.4',
        },
      },
      {
        id: 'dwp-4',
        code: 'PIN-04',
        name: 'Pin: Pressurized Subsea Housing Handover',
        date: 'Aug 24',
        status: 'upcoming',
        t: 0.94,
        pos: { x: 165, y: 495 },
        deliverableSummary: '600 bar rated titanium vessel pressure tested with leak rate <10^-9 mbar*l/s.',
      },
    ],
  },
];

export const INITIAL_GIGS: JobPosting[] = [
  {
    id: 'gig-01',
    title: 'Principal Aerothermal Systems Architect',
    discipline: 'Aerospace & Fluid Dynamics',
    location: 'London, UK / Remote',
    workType: 'Remote',
    postedBy: 'Marcus Vance, PE · Senior Partner, CasinWorks',
    clientCode: 'Client: Aethelgard Propulsion',
    securityClearance: 'UK SC / NATO Secret eligible',
    rate: '£165 – £195 / hr',
    duration: '6-month dedicated retainer',
    summary: 'Lead high-speed CFD mesh convergence and aerothermal heating analysis for a Mach 4+ passive leading-edge assembly.',
    deliverables: [
      'Validated shock-layer radiation coupling model',
      'Coupled finite-element thermal response charts in OpenFOAM/Ansys',
      'Executive technical memo for CDR board review',
    ],
    qualifications: [
      '10+ years in hypersonics or high-enthalpy gas dynamics',
      'Direct experience with high-temperature ceramics or refractory metals',
      'Demonstrated track record delivering mission-critical flight hardware',
    ],
  },
  {
    id: 'gig-02',
    title: 'Subsea Cryogenic Valve Specialist',
    discipline: 'Cryogenics & High-Pressure Fluidics',
    location: 'Zurich, CH / High-security Test Rig',
    workType: 'On-site',
    postedBy: 'Dr. Elena Rostova · Partner & Head of Mechanics, CasinWorks',
    clientCode: 'Client: North Sea Deep Energies',
    securityClearance: 'Non-disclosure Level 3',
    rate: 'CHF 220 / hr',
    duration: '8-week burst engagement',
    summary: 'Diagnose micro-cavitation phenomena and cryogenic elastomer seat compliance under cyclical 350-bar liquid nitrogen pulses.',
    deliverables: [
      'High-speed acoustic sensor telemetry analysis',
      'Redesigned seat seal cross-section with FEA stress analysis',
      'Cryogenic proof-test protocol and safety sign-off',
    ],
    qualifications: [
      'Master of Science or PhD in Mechanical or Fluid Engineering',
      'Deep mastery of cryogenic metallurgy and seal degradation mechanisms',
      'Experience in high-pressure oil & gas or rocket propulsion plumbing',
    ],
  },
  {
    id: 'gig-03',
    title: 'Guidance, Navigation & Control (GNC) Lead',
    discipline: 'Avionics & Control Theory',
    location: 'Boston, MA / Hybrid',
    workType: 'Hybrid',
    postedBy: 'David Sterling, CEng · Systems Principal, CasinWorks',
    clientCode: 'Client: Stratosphere Dynamics Corp',
    securityClearance: 'US DoD Secret required',
    rate: '$190 – $225 / hr',
    duration: '4-month milestone contract',
    summary: 'Synthesize robust multi-variable H-infinity flight control laws for an uncrewed atmospheric penetration vehicle under extreme turbulence.',
    deliverables: [
      'State-space control law model in MATLAB/Simulink with auto-coded C/C++',
      'Monte Carlo dispersion run analysis report (50,000 runs)',
      'Hardware-in-the-loop (HIL) lab verification bench testing',
    ],
    qualifications: [
      'Advanced flight dynamics and optimal control background',
      'Experience with RTOS execution and DO-178C Level A avionics standards',
      'Proven record on high-g dynamic stabilization platforms',
    ],
  },
  {
    id: 'gig-04',
    title: 'Titanium Additive DED Metallurgist',
    discipline: 'Materials Science & Manufacturing',
    location: 'Munich, DE / Remote',
    workType: 'Remote',
    postedBy: 'Marcus Vance, PE · Senior Partner, CasinWorks',
    clientCode: 'Client: Orbital Turbine Works',
    rate: '€150 – €180 / hr',
    duration: '3-month advisory retainer',
    summary: 'Optimize Directed Energy Deposition (DED) laser wire parameters for Ti-6Al-4V turbine housing to eliminate micro-porosity and residual stress.',
    deliverables: [
      'Process parameter matrix correlating laser beam scan speed to melt pool morphology',
      'EBSD grain-orientation and residual stress x-ray diffraction reports',
      'Post-deposition hot isostatic pressing (HIP) cycle specification',
    ],
    qualifications: [
      'PhD in Materials Science or Metallurgical Engineering',
      'Direct hands-on experience qualifying additive aero-engine components',
      'Proficiency in microstructural characterization (SEM, EDS, EBSD)',
    ],
  },
  {
    id: 'gig-05',
    title: 'High-Pressure Shock Tube Test Engineer',
    discipline: 'Experimental Mechanics & Diagnostics',
    location: 'Mojave, CA / Mojave Aerospace Port',
    workType: 'On-site',
    postedBy: 'Dr. Elena Rostova · Partner & Head of Mechanics, CasinWorks',
    clientCode: 'Client: Aethelgard Aerostructures',
    securityClearance: 'ITAR restricted',
    rate: '$175 / hr',
    duration: '5-week sprint',
    summary: 'Commission and operate a diaphragm-driven detonation tube apparatus capturing sub-millisecond pressure traces and schlieren optics.',
    deliverables: [
      'Piezo-electric PCB pressure transducer calibration documentation',
      'High-speed video archive at 250,000 fps with calibrated timing stamps',
      'Incident-shock velocity and reflected temperature deduction spreadsheets',
    ],
    qualifications: [
      'BS/MS in Aerospace or Mechanical Engineering',
      '5+ years experience running experimental high-explosive or shock-tube rigs',
      'Rigorous commitment to laboratory test safety and ITAR compliance',
    ],
  },
];

export const INITIAL_PROJECT_DOCUMENTS: ProjectDocument[] = [
  {
    id: 'doc-po-4471',
    projectId: 'tmp-andon',
    type: 'PO',
    title: 'Purchase Order #4471',
    subtitle: 'Uploaded Jun 3',
    date: 'Jun 3, 2026',
    status: 'Confirmed',
    fileName: 'PO_4471_TMP_Andon_Signed.pdf',
    fileSize: '342 KB',
    referenceNumber: 'PO-4471',
    amount: '₱480,000',
    numericAmount: 480000,
    notes: 'Approved by Toyota Motor Philippines procurement division.',
  },
  {
    id: 'doc-inv-ph1',
    projectId: 'tmp-andon',
    type: 'IN',
    title: 'Invoice — Phase 1',
    subtitle: 'Issued Jun 10',
    date: 'Jun 10, 2026',
    amount: '₱240,000',
    numericAmount: 240000,
    status: 'Paid',
    invoiceNumber: 'CW-INV-2026-041',
    dueDate: 'Jun 25, 2026',
    paidDate: 'Jun 12, 2026',
    lineItems: [
      {
        id: 'li-1',
        description: 'Phase 1 Kickoff & On-Site PLC Panel Hardware Installation',
        milestoneRef: 'WP-01: Hardware Install',
        quantity: 1,
        amount: 240000,
      },
    ],
    paymentInstructions: {
      bankName: 'Bank of the Philippine Islands (BPI)',
      accountName: 'CasinWorks Engineering Consultancy Inc.',
      accountNumber: '0041-8932-15',
      swiftBic: 'BOPIPHMM',
      branch: 'Ayala Triangle Branch, Makati City',
    },
  },
  {
    id: 'doc-rm-ph1',
    projectId: 'tmp-andon',
    type: 'RM',
    title: 'Remittance — Phase 1',
    subtitle: 'Uploaded Jun 12',
    date: 'Jun 12, 2026',
    amount: '₱240,000',
    numericAmount: 240000,
    status: 'Confirmed',
    fileName: 'BPI_WireReceipt_REF8829104.pdf',
    fileSize: '180 KB',
    referenceNumber: 'BPI-REF-8829104',
    notes: 'Verified by CasinWorks Finance Desk on Jun 13, 2026.',
  },
  {
    id: 'doc-inv-ph2',
    projectId: 'tmp-andon',
    type: 'IN',
    title: 'Invoice — Phase 2',
    subtitle: 'Issued Aug 16 · Due Aug 30',
    date: 'Aug 16, 2026',
    amount: '₱240,000',
    numericAmount: 240000,
    status: 'Awaiting payment',
    invoiceNumber: 'CW-INV-2026-082',
    dueDate: 'Aug 30, 2026',
    lineItems: [
      {
        id: 'li-2a',
        description: 'Phase 2 Milestone: Line Integration & Andon Trigger Protocol',
        milestoneRef: 'WP-02: Integration testing',
        quantity: 1,
        amount: 180000,
      },
      {
        id: 'li-2b',
        description: 'On-site Optical Sensor Interlock Certification & Telemetry Calibration',
        milestoneRef: 'WP-03: Pre-requisite milestone',
        quantity: 1,
        amount: 60000,
      },
    ],
    paymentInstructions: {
      bankName: 'Bank of the Philippine Islands (BPI)',
      accountName: 'CasinWorks Engineering Consultancy Inc.',
      accountNumber: '0041-8932-15',
      swiftBic: 'BOPIPHMM',
      branch: 'Ayala Triangle Branch, Makati City',
    },
  },
  {
    id: 'doc-rm-ph2',
    projectId: 'tmp-andon',
    type: 'RM',
    title: 'Remittance — Phase 2',
    subtitle: 'Not yet uploaded',
    date: 'Due Aug 30, 2026',
    amount: '₱240,000',
    numericAmount: 240000,
    status: 'Needs your upload',
    referenceNumber: '',
  },
];

